version: "3.9"
services:
  catalog:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - catalog_db

  catalog_db:
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: catalog_db
    volumes:
      - catalog-db-data:/var/lib/postgresql/data

volumes:
  catalog-db-data:
